export const ASYNC_COUNT_INCREMENT = "ASYNC_COUNT_INCREMENT";
export const ASYNC_COUNT_TIMES = "ASYNC_COUNT_TIMES";
export const ASYNC_COUNT_MINUS = "ASYNC_COUNT_MINUS";
export const ASYNC_COUNT_DIVIDE = "ASYNC_COUNT_DIVIDE";